const CHANGEWEB3 = "CHANGEWEB3";
const CHANGEACCOUNT = "CHANGEACCOUNT";
const CHANGEDATARRAY = "CHANGEADATAARRAY";
const CHANGEADDRESSES = "CHANGEADDRESSES";
const CHANGEOWNERS = "CHANGEOWNERS";
const CHAGNEINVESTMENTLISTONLOAD = "CHAGNEINVESTMENTLISTONLOAD";

export {
  CHANGEWEB3,
  CHANGEACCOUNT,
  CHANGEDATARRAY,
  CHANGEADDRESSES,
  CHANGEOWNERS,
  CHAGNEINVESTMENTLISTONLOAD,
};
